### ISSUE TITLE
QuasiRecomb crashes on single-CPU machines.

### ISSUE THREAD

**Issue by riccardomurri** [cbg-ethz/QuasiRecomb#1]
Hello,

I have been trying to run QuasiRecomb on a single processor machine
with no luck.

The program starts, completes the parsing phase, and -as soon as
"computing" appears on the screen- the following Java exception is
thrown:

```
    Exception in thread "main" java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:606)
            at com.simontuffs.onejar.Boot.run(Boot.java:340)
            at com.simontuffs.onejar.Boot.main(Boot.java:166)
    Caused by: java.lang.ExceptionInInitializerError
            at ch.ethz.bsse.quasirecomb.utils.Utils.parseBAMSAMPure(Utils.java:323)
            at ch.ethz.bsse.quasirecomb.utils.Utils.parseBAMSAM(Utils.java:399)
            at ch.ethz.bsse.quasirecomb.utils.Utils.parseInput(Utils.java:285)
            at ch.ethz.bsse.quasirecomb.model.Preprocessing.workflow(Preprocessing.java:68)
            at ch.ethz.bsse.quasirecomb.Startup.train(Startup.java:874)
            at ch.ethz.bsse.quasirecomb.Startup.doMain(Startup.java:923)
            at ch.ethz.bsse.quasirecomb.Startup.main(Startup.java:61)
            ... 6 more
    Caused by: java.lang.IllegalArgumentException
            at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:225)
            at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:210)
            at ch.ethz.bsse.quasirecomb.informationholder.Threading.<clinit>(Threading.java:36)
            ... 13 more
```

I have tried different versions of Java, to no avail.

The exact same setup on a multi-core machine works correctly without
any problem.

If QuasiRecomb cannot run on a single-core system, it should at least
exit with a sensible error message...

**Comment by senaj** [comment]
Hi,

In the recommendation for aligning reads with bwa-mem for use with Quasirecomb, the -t option is set to 79. According to the bwa manual the -t option is to set the number of threads. Are you recommending to run bwa-mem with 79 threads or should we use the -T option, which would not output alignments with scores lower than 79? Or, am I miss interpreting what -t is specifying?

Also, when using bam files generated from bwa-mem, we should filter the bam file using samtools and only use mapped reads for our Quasirecomb input?

Thank you very much for your help?

BWA is a good alternative to create an alignment with following bash script:

function alignMem () {
    bwa index -a bwtsw $2;
    bwa mem -B 20 -A 3 -O 30 -E 3 -t 79 $2 $1 $3 > aln.sam;
    samtools faidx $2;
    samtools view -bt $2.fai aln.sam > aln.bam;
    samtools sort aln.bam aln-sorted;
    samtools index aln-sorted.bam;
    rm aln.sam aln.bam;
    samtools view -bq 1 -F 4 aln-sorted.bam > reads.bam;
    rm aln*;
    samtools index reads.bam
}

**Comment by riccardomurri** [comment]
... so, closing without any note or comment at all?

**Comment by armintoepfer** [comment]
If it's that important to you, finding that line shouldn't have been be too hard. Feel free to patch, test, and pull request it: https://github.com/cbg-ethz/QuasiRecomb/blob/master/src/main/java/ch/ethz/bsse/quasirecomb/informationholder/Threading.java#L36
