### ISSUE TITLE
ParsingException in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by antonkratz** [cbg-ethz/QuasiRecomb#9]
I want to determine coverage, following the [Beginners' guide to viral population inference](https://github.com/cbg-ethz/QuasiRecomb/blob/master/HOWTO.md):
`java -jar QuasiRecomb.jar -i xyz.sam -coverage`. I immediately crash into the error below. I tried different versions of java, including
```bash
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
on Intel architecture and
```bash
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
```
on M3 architecture. This is under ubuntu.

Could you please advise how to get QuasiRecomb running?

```bash
00:00:00 ParsingException in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.UnsupportedOperationException
        at net.sf.samtools.SAMTextReader.getIndex(SAMTextReader.java:104)
        at net.sf.samtools.SAMFileReader.getIndex(SAMFileReader.java:275)
        at ch.ethz.bsse.quasirecomb.utils.Utils.parseBAMSAMPure(Utils.java:296)
        at ch.ethz.bsse.quasirecomb.utils.Utils.parseBAMSAM(Utils.java:399)
        at ch.ethz.bsse.quasirecomb.utils.Utils.parseInput(Utils.java:285)
        at ch.ethz.bsse.quasirecomb.model.Preprocessing.workflow(Preprocessing.java:68)
        at ch.ethz.bsse.quasirecomb.Startup.train(Startup.java:874)
        at ch.ethz.bsse.quasirecomb.Startup.doMain(Startup.java:923)
        at ch.ethz.bsse.quasirecomb.Startup.main(Startup.java:61)
        ... 6 more
```

**Comment by armintoepfer** [comment]
Input needs to be a BAM, not SAM. From the stack trace you can see that it asks for an index too. So convert to BAM and index it using samtools.

**Comment by antonkratz** [comment]
Thank you for the prompt reply! Yes, I can now confirm it works with sorted bam!

(I was just following the Beginner's guide, which states to `java -jar QuasiRecomb.jar -i reads.sam -coverage`.)
